apiVersion: v1
kind: Pod
metadata:
  name: sysctl-example
spec:
  containers:
  - name: busybox
    image: busybox
    command: [ "sh", "-c", "sleep 12000" ]
    securityContext:
      runAsUser: 2000
      capabilities:
        add: ["NET_ADMIN"]