apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: alpine
        imagePullPolicy: Always
        args:
        - ping
        - 127.0.0.1
        name: alpine
        env:
        ######### 配置 环境变量 ###########
        ######### 配置 project，如果使用k8s集群默认的project可以不填 ###########
        - name: aliyun_logs_test-stdout_project
          value: k8s-log-xxx
        - name: aliyun_logs_test-file_project
          value: k8s-log-xxx
        ######### 配置 机器组，如果使用k8s集群默认的project下的默认机器组可以不填 ###########
        - name: aliyun_logs_test-stdout_machinegroup
          value: k8s-group-app-alpine
        - name: aliyun_logs_test-file_machinegroup
          value: k8s-group-app-alpine
        ######### 设置标准输出和错误输出的logstore test-stdout###########
        - name: aliyun_logs_test-stdout
          value: stdout
        ######### 将/log/*.log目录下的日志收集到logstore test-file###########
        ######### 注：除了标准输出和错误输出，其他的自定义收集目录必须挂载emptyDirVolume，否者无法收集###########
        ######### 注：比如/log/目录就需要挂载emptyDirVolume，如下###########
        - name: aliyun_logs_test-file
          value: /log/*.log
        ######### 日志保留时间，只对单个logstore生效 ###########
        - name: aliyun_logs_test-stdout_ttl
          value: "7"
        ######### 日志分区数，只对单个logstore生效 ###########
        - name: aliyun_logs_test-stdout_shard
          value: "2"
        #################################
        ######### 配置vulume mount，该volume就是为了上面的自定义的日志收集目录#######
        volumeMounts:
        - name: volume-sls
          mountPath: /log
      volumes:
      - name: volume-sls