apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    "k8s.aliyun.com/eci-instance-type": "ecs.c6.xlarge"
spec:
  nodeName: virtual-kubelet
  containers:
  - image: nginx
    name: nginx