apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  annotations:
    "k8s.aliyun.com/eci-gpu-type": "P4"
spec:
  nodeName: virtual-kubelet
  containers:
  - image: registry-vpc.cn-beijing.aliyuncs.com/lxx/cos-4g
    name: gpu-test

---
####也可以直接指定规格
apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  annotations:
    "k8s.aliyun.com/eci-instance-type": "ecs.gn5i-c2g1.large"
spec:
  nodeName: virtual-kubelet
  containers:
  - image: registry-vpc.cn-beijing.aliyuncs.com/lxx/cos-4g
    name: gpu-test
