apiVersion: v1
kind: Pod
metadata:
  name: vk-downward-down-volume
  annotations:
    regionId: cn-beijing
    platform: Aliyun ECI
  labels:
    app: nginx
    env: test
spec:
  nodeName: virtual-kubelet
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - name: podinfo
        mountPath: /etc/podinfo
        readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "metadata.name"
            fieldRef:
              fieldPath: metadata.name
          - path: "metadata.namespace"
            fieldRef:
              fieldPath: metadata.namespace
          - path: "metadata.uid"
            fieldRef:
              fieldPath: metadata.uid
          - path: "metadata.labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "metadata.annotations"
            fieldRef:
              fieldPath: metadata.annotations