apiVersion: v1
kind: Pod
metadata:
  name: vk-downward-env
  annotations:
    regionId: cn-beijing
    platform: Aliyun ECI
  labels:
    app: nginx
    env: test
spec:
  nodeName: virtual-kubelet
  containers:
  - image: nginx
    name: nginx
    env:
      - name: MY_metadata.name
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_metadata.namespace
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_metadata.uid
        valueFrom:
          fieldRef:
            fieldPath: metadata.uid
      - name: MY_metadata.labels
        valueFrom:
          fieldRef:
            fieldPath: metadata.labels['env']
      - name: MY_metadata.annotations
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['regionId']
      - name: MY_status.podIP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: MY_spec.serviceAccountName
        valueFrom:
          fieldRef:
            fieldPath: spec.serviceAccountName
      - name: MY_spec.nodeName
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName