apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpine
  name: alpine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - image: alpine
        imagePullPolicy: Always
        args:
        - ping
        - 127.0.0.1
        name: alpine
        env:
        ######### 配置 环境变量 ###########
        ######### 配置 project，如果使用k8s集群默认的project可以不填###########
        - name: aliyun_logs_project
          value: k8s-xxx
        ######### 配置 机器组，如果使用k8s集群默认的project下的默认机器组可以不填###########
        - name: aliyun_logs_machinegroup
          value: k8s-group-xxx
        - name: aliyun_logs_test-stdout
          value: stdout
        - name: aliyun_logs_test-file
          value: /log/*.log
        ######### 日志保留时间，只对单个logstore生效###########
        - name: aliyun_logs_test-stdout_ttl
          value: 7
        ######### 日志分区数，只对单个logstore生效###########
        - name: aliyun_logs_test-stdout_shard
          value: 2
        #################################
        ######### 配置vulume mount #######
        volumeMounts:
        - name: volume-sls
          mountPath: /log
      volumes:
      - name: volume-sls